# Generated by Django 2.2.4 on 2019-08-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='create_invoice',
            fields=[
                ('date_created', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('month', models.CharField(blank=True, max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete='CASCADE', to='trucks.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('date_handled', models.DateField(blank=True, null=True)),
                ('truck_no', models.CharField(max_length=50)),
                ('container', models.CharField(max_length=11)),
                ('exporter', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('entry_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete='CASCADE', to='trucks.Client')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(blank=True, null=True)),
                ('amount_paid', models.CharField(max_length=50)),
                ('invoice_paid', models.ForeignKey(on_delete='CASCADE', to='trucks.create_invoice')),
            ],
        ),
    ]
