# Generated by Django 2.2.4 on 2019-08-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_paid',
        ),
        migrations.RemoveField(
            model_name='trucks',
            name='user',
        ),
        migrations.AlterField(
            model_name='trucks',
            name='client',
            field=models.ForeignKey(on_delete='CASCADE', to='client_app.Client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='create_invoice',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
