# Generated by Django 2.2.4 on 2019-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_invoice',
            fields=[
                ('date_created', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('month', models.CharField(blank=True, max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete='CASCADE', to='trucks.Client')),
            ],
        ),
        migrations.RemoveField(
            model_name='trucks',
            name='id',
        ),
        migrations.AddField(
            model_name='trucks',
            name='date_handled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trucks',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trucks',
            name='exporter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trucks',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='container',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='entry_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(blank=True, null=True)),
                ('amount_paid', models.CharField(max_length=50)),
                ('invoice_paid', models.ForeignKey(on_delete='CASCADE', to='trucks.create_invoice')),
            ],
        ),
    ]
