# Generated by Django 2.2.1 on 2019-06-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20190626_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_paid', models.CharField(max_length=8)),
                ('date_paid', models.CharField(max_length=8)),
                ('amount_paid', models.CharField(max_length=100)),
                ('paid_by', models.CharField(max_length=10)),
                ('balance', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='trucks',
            name='date',
            field=models.CharField(default='28/06/2019', max_length=8),
        ),
    ]
