# Generated by Django 2.2.1 on 2019-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20190712_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucks',
            name='container',
            field=models.CharField(max_length=11),
        ),
    ]
