# Generated by Django 2.2.1 on 2019-06-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_auto_20190628_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='client',
            field=models.ForeignKey(default='0', on_delete='CASCADE', to='trucks.Client'),
        ),
    ]
