# Generated by Django 2.2.1 on 2019-06-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0007_auto_20190628_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='client',
        ),
        migrations.AlterField(
            model_name='trucks',
            name='date',
            field=models.CharField(default='', max_length=8),
        ),
    ]
