# Generated by Django 2.2.1 on 2019-06-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0008_auto_20190628_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucks',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='exporter',
            field=models.CharField(default='', max_length=50),
        ),
    ]
