# Generated by Django 2.2.1 on 2019-07-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0009_auto_20190628_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payments',
        ),
        migrations.RemoveField(
            model_name='trucks',
            name='date',
        ),
        migrations.AlterField(
            model_name='trucks',
            name='description',
            field=models.CharField(default='cleared', max_length=50),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='exporter',
            field=models.CharField(default='cleared', max_length=50),
        ),
    ]
