# Generated by Django 2.2.4 on 2019-08-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_invoice',
            fields=[
                ('date_created', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('month', models.CharField(blank=True, max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(blank=True, null=True)),
                ('amount_paid', models.CharField(max_length=50)),
                ('invoice_paid', models.ForeignKey(on_delete='CASCADE', to='accounts_app.create_invoice')),
            ],
        ),
    ]
